version: 0.2

phases: 
    install:
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        # commands: 
            # - cd src
            # - npm install
            # - npm run build
        commands: ./.pipeline/build.sh

    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
    files:
        - './src/dist/**/*'
            